# # -*- coding: utf-8 -*-
# # """Text-Summarization-NLP.ipynb

# # Automatically generated by Colab.

# # Original file is located at
# #     https://colab.research.google.com/drive/1Wp3a5ROLzYNntOrrKlKzzJIRw0LBi5F4
# # """

# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns

# # """# Problem Statement
# # To automatically summarize long customer reviews into short and meaningful summaries using NLP techniques
# # # """



# # """# Understand Data"""

# # from google.colab import files
# # data=files.upload("")

# data=pd.read_csv("Reviews.csv")

# print(data.head())

# print(data.info)

# print(data.shape)

# print(data.columns)

# print(data.isnull().sum())


# print(data[['Text', 'Summary']].head(10))
# data = data.dropna(subset=['Summary'])
# print(data.head())
# print("\n**********Text Preprocessing***********\n")
# # Text Preprocessing

# print(data['Text'].iloc[0])
# print(data['Summary'].iloc[0])
# import re


# data['Text'] = data['Text'].str.lower()
# import re

# # Sentence Tokenization

# import nltk
# nltk.download('punkt_tab')

# from nltk.tokenize import sent_tokenize

# text = data['Text'].iloc[0]

# sentences = sent_tokenize(text)

# print(sentences)
# print("Number of sentences:", len(sentences))

# from sklearn.feature_extraction.text import TfidfVectorizer

# vectorizer = TfidfVectorizer(stop_words='english')

# tfidf_matrix = vectorizer.fit_transform(sentences)

# print(tfidf_matrix)

# sentence_scores = tfidf_matrix.sum(axis=1)
# sentence_scores = sentence_scores.A1

# print(sentence_scores)
# for i, score in enumerate(sentence_scores):
#     print("Sentence", i + 1, ":", score)
#     print(sentences[i])
#     print()
    
# top_n = 1

# top_indices = sentence_scores.argsort()[-top_n:]

# top_indices = sorted(top_indices)

# summary = " ".join(sentences[i] for i in top_indices)

# print("Original Text:")
# print(text)

# print("\nGenerated Summary:")
# print(summary)

# from rouge_score import rouge_scorer

# reference = data['Summary'].iloc[0]
# generated = summary

# scorer = rouge_scorer.RougeScorer(
#     ['rouge1', 'rouge2', 'rougeL'],
#     use_stemmer=True
# )

# scores = scorer.score(reference, generated)

# print("ROUGE-1:", scores['rouge1'])
# print("ROUGE-2:", scores['rouge2'])
# print("ROUGE-L:", scores['rougeL'])

# generated_summaries = []
   
# sample_data = data.head(100)

# for text in sample_data['Text']:
    
#     sentences = sent_tokenize(text)
    
#     if len(sentences) <= 1:
#         generated_summaries.append(text)
#         continue
    
#     vectorizer = TfidfVectorizer(stop_words='english')
#     tfidf_matrix = vectorizer.fit_transform(sentences)
    
#     sentence_scores = tfidf_matrix.sum(axis=1).A1
    
#     top_n = min(2, len(sentences))
    
#     top_indices = sentence_scores.argsort()[-top_n:]
#     top_indices = sorted(top_indices)
    
#     summary = " ".join(sentences[i] for i in top_indices)
    
#     generated_summaries.append(summary)
 

# print("Number of reviews:", len(sample_data))
   
    
# top_indices = sentence_scores.argsort()[-top_n:]
# top_indices = sorted(top_indices)
    
# summary = " ".join(sentences[i] for i in top_indices)
    
# generated_summaries.append(summary)

# print("Generated summaries:", len(generated_summaries))

# print("Generated summaries:", len(generated_summaries))
# print("ORIGINAL:")
# print(sample_data['Text'].iloc[0])

# print("\nHUMAN SUMMARY:")
# print(sample_data['Summary'].iloc[0])

# print("\nGENERATED SUMMARY:")
# print(generated_summaries[0])

# rouge1_scores = []
# rouge2_scores = []
# rougeL_scores = []

# for reference, generated in zip(
#     sample_data['Summary'],
#     generated_summaries
# ):
    
#     scores = scorer.score(reference, generated)
    
#     rouge1_scores.append(scores['rouge1'].fmeasure)
#     rouge2_scores.append(scores['rouge2'].fmeasure)
#     rougeL_scores.append(scores['rougeL'].fmeasure)
# print("Average ROUGE-1:", sum(rouge1_scores) / len(rouge1_scores))
# print("Average ROUGE-2:", sum(rouge2_scores) / len(rouge2_scores))
# print("Average ROUGE-L:", sum(rougeL_scores) / len(rougeL_scores))

# -*- coding: utf-8 -*-

# ============================================================
# TEXT SUMMARIZATION USING NLP
# Amazon Fine Food Reviews Dataset
# ============================================================


# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk

from nltk.tokenize import sent_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from rouge_score import rouge_scorer


# ============================================================
# 2. PROBLEM STATEMENT
# ============================================================

# To automatically summarize long customer reviews
# into short and meaningful summaries using NLP techniques.


# ============================================================
# 3. LOAD DATASET
# ============================================================

data = pd.read_csv("Reviews.csv")

print("First 5 rows:")
print(data.head())

print("\nDataset Information:")
data.info()

print("\nDataset Shape:")
print(data.shape)

print("\nDataset Columns:")
print(data.columns)

print("\nMissing Values:")
print(data.isnull().sum())


# ============================================================
# 4. VIEW TEXT AND SUMMARY
# ============================================================

print("\nText and Summary:")
print(data[['Text', 'Summary']].head(10))


# ============================================================
# 5. HANDLE MISSING VALUES
# ============================================================

# Summary is needed later as the human-written reference
# for evaluation, so remove rows where Summary is missing.

data = data.dropna(subset=['Summary'])

print("\nShape after removing missing Summary:")
print(data.shape)


# ============================================================
# 6. BASIC TEXT PREPROCESSING
# ============================================================

# Convert review text to lowercase.
# We keep punctuation because sentence tokenization needs it.

data['Text'] = data['Text'].str.lower()

print("\nFirst Review:")
print(data['Text'].iloc[0])

print("\nHuman Summary:")
print(data['Summary'].iloc[0])


# ============================================================
# 7. DOWNLOAD NLTK SENTENCE TOKENIZER
# ============================================================

nltk.download('punkt_tab')


# ============================================================
# 8. SENTENCE TOKENIZATION
# ============================================================

# Take the first review.

text = data['Text'].iloc[0]

# Split the review into separate sentences.

sentences = sent_tokenize(text)

print("\nSentences:")
print(sentences)

print("\nNumber of sentences:", len(sentences))


# ============================================================
# 9. TF-IDF
# ============================================================

vectorizer = TfidfVectorizer(stop_words='english')

tfidf_matrix = vectorizer.fit_transform(sentences)

print("\nTF-IDF Matrix:")
print(tfidf_matrix)

print("\nTF-IDF Matrix Shape:")
print(tfidf_matrix.shape)


# ============================================================
# 10. SENTENCE SCORING
# ============================================================

# Add the TF-IDF scores of all words in each sentence.

sentence_scores = tfidf_matrix.sum(axis=1)

# Convert scores into a normal NumPy array.

sentence_scores = sentence_scores.A1

print("\nSentence Scores:")
print(sentence_scores)


# Display every sentence with its score.

print("\nSentence Importance:")

for i, score in enumerate(sentence_scores):
    print("Sentence", i + 1, ":", score)
    print(sentences[i])
    print()


# ============================================================
# 11. GENERATE SUMMARY - TOP 2 SENTENCES
# ============================================================

top_n = 2

top_indices = sentence_scores.argsort()[-top_n:]

# Keep original sentence order.

top_indices = sorted(top_indices)

summary = " ".join(sentences[i] for i in top_indices)

print("\nOriginal Text:")
print(text)

print("\nGenerated Summary:")
print(summary)


# ============================================================
# 12. HUMAN SUMMARY VS GENERATED SUMMARY
# ============================================================

reference = data['Summary'].iloc[0]
generated = summary

print("\nHuman Summary:")
print(reference)

print("\nGenerated Summary:")
print(generated)


# ============================================================
# 13. ROUGE EVALUATION - SINGLE REVIEW
# ============================================================

scorer = rouge_scorer.RougeScorer(
    ['rouge1', 'rouge2', 'rougeL'],
    use_stemmer=True
)

scores = scorer.score(reference, generated)

print("\nSingle Review ROUGE Scores:")

print("ROUGE-1:", scores['rouge1'])
print("ROUGE-2:", scores['rouge2'])
print("ROUGE-L:", scores['rougeL'])


# ============================================================
# 14. TEST ON 100 REVIEWS
# ============================================================

sample_data = data.head(100)

print("\nNumber of reviews used for testing:")
print(len(sample_data))


# ============================================================
# 15. GENERATE SUMMARIES FOR 100 REVIEWS
# ============================================================

generated_summaries = []

for text in sample_data['Text']:

    sentences = sent_tokenize(text)

    # If review has only one sentence,
    # use the original review as the summary.

    if len(sentences) <= 1:
        generated_summaries.append(text)
        continue

    # TF-IDF for current review.

    vectorizer = TfidfVectorizer(stop_words='english')

    tfidf_matrix = vectorizer.fit_transform(sentences)

    # Calculate sentence scores.

    sentence_scores = tfidf_matrix.sum(axis=1).A1

    # Select top 2 sentences.

    top_n = min(2, len(sentences))

    top_indices = sentence_scores.argsort()[-top_n:]

    # Keep original order.

    top_indices = sorted(top_indices)

    # Create summary.

    summary = " ".join(sentences[i] for i in top_indices)

    generated_summaries.append(summary)


print("\nGenerated summaries:", len(generated_summaries))


# ============================================================
# 16. CHECK ONE GENERATED SUMMARY
# ============================================================

print("\n==============================")
print("FIRST REVIEW RESULT")
print("==============================")

print("\nORIGINAL REVIEW:")
print(sample_data['Text'].iloc[0])

print("\nHUMAN SUMMARY:")
print(sample_data['Summary'].iloc[0])

print("\nGENERATED SUMMARY:")
print(generated_summaries[0])


# ============================================================
# 17. ROUGE EVALUATION ON 100 REVIEWS
# ============================================================

rouge1_scores = []
rouge2_scores = []
rougeL_scores = []


for reference, generated in zip(
    sample_data['Summary'],
    generated_summaries
):

    scores = scorer.score(reference, generated)

    rouge1_scores.append(scores['rouge1'].fmeasure)
    rouge2_scores.append(scores['rouge2'].fmeasure)
    rougeL_scores.append(scores['rougeL'].fmeasure)


# ============================================================
# 18. AVERAGE ROUGE SCORES
# ============================================================

average_rouge1 = sum(rouge1_scores) / len(rouge1_scores)
average_rouge2 = sum(rouge2_scores) / len(rouge2_scores)
average_rougeL = sum(rougeL_scores) / len(rougeL_scores)


print("\n==============================")
print("AVERAGE ROUGE SCORES")
print("==============================")

print("Average ROUGE-1:", average_rouge1)
print("Average ROUGE-2:", average_rouge2)
print("Average ROUGE-L:", average_rougeL)


# ============================================================
# 19. MODEL IMPROVEMENT EXPERIMENT
# TOP 1 SENTENCE
# ============================================================

generated_summaries_1 = []


for text in sample_data['Text']:

    sentences = sent_tokenize(text)

    if len(sentences) <= 1:
        generated_summaries_1.append(text)
        continue

    vectorizer = TfidfVectorizer(stop_words='english')

    tfidf_matrix = vectorizer.fit_transform(sentences)

    sentence_scores = tfidf_matrix.sum(axis=1).A1

    # Select only top 1 sentence.

    top_n = 1

    top_indices = sentence_scores.argsort()[-top_n:]

    top_indices = sorted(top_indices)

    summary = " ".join(sentences[i] for i in top_indices)

    generated_summaries_1.append(summary)


print("\nTop 1 summaries generated:", len(generated_summaries_1))


# ============================================================
# 20. ROUGE EVALUATION FOR TOP 1
# ============================================================

rouge1_top1 = []
rouge2_top1 = []
rougeL_top1 = []


for reference, generated in zip(
    sample_data['Summary'],
    generated_summaries_1
):

    scores = scorer.score(reference, generated)

    rouge1_top1.append(scores['rouge1'].fmeasure)
    rouge2_top1.append(scores['rouge2'].fmeasure)
    rougeL_top1.append(scores['rougeL'].fmeasure)


# ============================================================
# 21. AVERAGE ROUGE - TOP 1
# ============================================================

average_rouge1_top1 = sum(rouge1_top1) / len(rouge1_top1)
average_rouge2_top1 = sum(rouge2_top1) / len(rouge2_top1)
average_rougeL_top1 = sum(rougeL_top1) / len(rougeL_top1)


print("\n==============================")
print("TOP 1 SENTENCE ROUGE SCORES")
print("==============================")

print("Average ROUGE-1:", average_rouge1_top1)
print("Average ROUGE-2:", average_rouge2_top1)
print("Average ROUGE-L:", average_rougeL_top1)


# ============================================================
# 22. TOP 1 VS TOP 2 COMPARISON
# ============================================================

print("\n==============================")
print("TOP 1 VS TOP 2")
print("==============================")

print("\nTOP 2:")
print("ROUGE-1:", average_rouge1)
print("ROUGE-2:", average_rouge2)
print("ROUGE-L:", average_rougeL)

print("\nTOP 1:")
print("ROUGE-1:", average_rouge1_top1)
print("ROUGE-2:", average_rouge2_top1)
print("ROUGE-L:", average_rougeL_top1)

print("\n==============================")
print("MODEL COMPARISON")
print("==============================")

print("\nTop 2 Sentences:")
print("ROUGE-1:", average_rouge1)
print("ROUGE-2:", average_rouge2)
print("ROUGE-L:", average_rougeL)

print("\nTop 1 Sentence:")
print("ROUGE-1:", average_rouge1_top1)
print("ROUGE-2:", average_rouge2_top1)
print("ROUGE-L:", average_rougeL_top1)
for i in range(5):

    print("\n==============================")
    print("REVIEW", i + 1)
    print("==============================")

    print("\nHUMAN SUMMARY:")
    print(sample_data['Summary'].iloc[i])

    print("\nGENERATED SUMMARY:")
    print(generated_summaries[i])
generated_summaries_mean = []

sample_data = data.head(100)

for text in sample_data['Text']:

    sentences = sent_tokenize(text)

    if len(sentences) <= 1:
        generated_summaries_mean.append(text)
        continue

    vectorizer = TfidfVectorizer(stop_words='english')

    tfidf_matrix = vectorizer.fit_transform(sentences)

    # Mean TF-IDF score
    sentence_scores = tfidf_matrix.mean(axis=1).A1

    # Select top 2 sentences
    top_n = min(2, len(sentences))

    top_indices = sentence_scores.argsort()[-top_n:]

    # Keep original sentence order
    top_indices = sorted(top_indices)

    summary = " ".join(sentences[i] for i in top_indices)

    generated_summaries_mean.append(summary)


print("Mean TF-IDF summaries:", len(generated_summaries_mean))
rouge1_mean = []
rouge2_mean = []
rougeL_mean = []

for reference, generated in zip(
    sample_data['Summary'],
    generated_summaries_mean
):

    scores = scorer.score(reference, generated)

    rouge1_mean.append(scores['rouge1'].fmeasure)
    rouge2_mean.append(scores['rouge2'].fmeasure)
    rougeL_mean.append(scores['rougeL'].fmeasure)
average_rouge1_mean = sum(rouge1_mean) / len(rouge1_mean)
average_rouge2_mean = sum(rouge2_mean) / len(rouge2_mean)
average_rougeL_mean = sum(rougeL_mean) / len(rougeL_mean)

print("Mean TF-IDF ROUGE-1:", average_rouge1_mean)
print("Mean TF-IDF ROUGE-2:", average_rouge2_mean)
print("Mean TF-IDF ROUGE-L:", average_rougeL_mean)
print("\n==============================")
print("FINAL MODEL EXPERIMENTS")
print("==============================")

print("\n1. TF-IDF Sum + Top 2")
print("ROUGE-1:", average_rouge1)
print("ROUGE-2:", average_rouge2)
print("ROUGE-L:", average_rougeL)

print("\n2. TF-IDF Sum + Top 1")
print("ROUGE-1:", average_rouge1_top1)
print("ROUGE-2:", average_rouge2_top1)
print("ROUGE-L:", average_rougeL_top1)

print("\n3. TF-IDF Mean + Top 2")
print("ROUGE-1:", average_rouge1_mean)
print("ROUGE-2:", average_rouge2_mean)
print("ROUGE-L:", average_rougeL_mean)